<table>
    <?php foreach ($users as $user): ?>
        <tr>
            <td>
                <?= $user ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>

<form action="/users" method="get">
    <input type="search" name="name" value="<?= $name ? htmlspecialchars($name) : '' ?>" />
    <input type="submit" value="Search" />
</form>
<!-- END -->
<h3><?php $flash ? print_r($flash) : ''; ?></h3>