<table>
    <?php foreach ($users as $user): ?>
        <tr>
            <td>
                <a href="/users/<?= $user["id"] ?>"><?= htmlspecialchars($user["name"]) ?></a>
                <span>|</span>
                <a href="/users/<?= $user["id"] ?>/edit">edit <?= htmlspecialchars($user["name"]) ?></a>
            </td>
        </tr>
    <?php endforeach ?>
</table>

<form action="/users" method="get">
    <input type="search" name="name" value="<?= $name ? htmlspecialchars($name) : '' ?>" />
    <input type="submit" value="Search" />
</form>
<!-- END -->
<h3><?php $flash ? print_r($flash) : ''; ?></h3>

<form action="/auth" method="post">
    <input type="email" required name="auth[email]" value="<?= htmlspecialchars($auth['email']) ?>">
    <?php if (isset($errors['authemail'])): ?>
        <div><?= $errors['authemail'] ?></div>
    <?php endif ?>
    <input type="submit" value="Login" />
</form>

<?php print_r($_SESSION); ?>
<?php /* if(isset($user)): ?>
    <div>Залогинен товарищ <?= $user['email'] ?></div>
<?php else: ?>
    <form action="/auth" method="post">
        <input type="email" required name="auth[email]" value="<?= htmlspecialchars($auth['email']) ?>">
        <?php if (isset($errors['authemail'])): ?>
            <div><?= $errors['authemail'] ?></div>
        <?php endif ?>
        <input type="submit" value="Login" />
    </form>
<?php endif; */ ?>

